### ISSUE TITLE
Allow detailed information in Production Mode

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/ErrorWindowAddon#1]
As a QA tester 
I want to display detailed error information in production mode
So that I'm able to test the very same artifact and settings that will be promoted to production, and at the same time I can avoid looking into the logs in order to report the full stack trace.

**Comment by mlopezFC** [comment]
Given that the V14 version decides whether if it's in production mode based on a system property, I was thinking about doing something similar with V8 version: If "productionMode" system property is present, it has more priority than production mode obtained from Vaadin deployment configuration. In this case, the addon will continue to work in the same manner as before, but it's going to be possible to override the behavior in staging just by passing a system property.
