### ISSUE TITLE
Feature request: make the ErrorWindow internationalizable

### ISSUE THREAD

**Issue by michaelknigge** [FlowingCode/ErrorWindowAddon#16]
It would be great if the labels of the ErrorWindow could be customizable. This would make it possible to use language specific labels.

**Comment by michaelknigge** [comment]
I've created a PR for this, see https://github.com/FlowingCode/ErrorWindowAddon/pull/17

**Comment by mlopezFC** [comment]
Thanks @michaelknigge for the contribution (both the issue and the PR)!
As you already might know we are reviewing the changes, will let you know when we have news.
Regards!

**Comment by javier-godoy** [comment]
Version 3.1.0 have been published in Vaadin directory.
