### ISSUE TITLE
Improve ErrorWindow styles

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/ErrorWindowAddon#35]
- The message below the title should have `word-break: break-all`.

![image](https://user-images.githubusercontent.com/11554739/131831835-e1e44cd5-bda1-443f-bc3a-a82ca026b6f6.png)

- That element should have a css class so that it can be targeted for styling (with a sane CSS selector)
![image](https://user-images.githubusercontent.com/11554739/131832158-80e3e3ed-81e0-4b8c-b3c9-130fc953c0e2.png)

- That element is a  `span` (which is an inline element). In production mode, there is a `div` (which is a block element) inside of it.
![image](https://user-images.githubusercontent.com/11554739/131832028-145d5d8c-78dd-4add-ad10-4a2d634086f9.png)

**Comment by mlopezFC** [comment]
@javier-godoy Do you think that something like this would be fine?
![image](https://github.com/FlowingCode/ErrorWindowAddon/assets/28312758/4f9e7ddd-f9cf-4cc0-8910-2405bd9a2085)
