### ISSUE TITLE
Vaadin 24.2 error in Demo

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/ErrorWindowAddon#65]
Running the add-on demo in Vaadin 24.2, the "Navigation Error" button fails with:
```
java.lang.NoSuchMethodError: 'void com.vaadin.flow.component.UI.navigate(java.lang.Class)'
	at com.flowingcode.vaadin.addons.errorwindow.ErrorwindowDemo.lambda$new$9b1b5227$2(ErrorwindowDemo.java:127)
```

**Comment by paodb** [comment]
Seems to be a binary compatibility issue. Add-on is compiled using Vaadin version 14, in that version method returns [void](https://github.com/vaadin/flow/blob/ac7d44ae4cad51a4cdbee753884a78438b138bb3/flow-server/src/main/java/com/vaadin/flow/component/UI.java#L862). In Vaadin 24.2 navigate method [changed its return type](https://github.com/vaadin/flow/blob/3c2bdaf38fa7598eb9feec5a0b2a46255e7b8dcd/flow-server/src/main/java/com/vaadin/flow/component/UI.java#L896) .
