### ISSUE TITLE
Support for obtaining production/development mode from Vaadin in Vaadin 24

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/ErrorWindowAddon#79]
### Feature proposal

Right now the implementation defines if the mode is production or not, [based on a system property](https://github.com/FlowingCode/ErrorWindowAddon/blob/master/src/main/java/com/flowingcode/vaadin/addons/errorwindow/ErrorWindowFactory.java#L40).
In Vaadin 24 it is possible to obtain that configuration programatically. It would be great that by default that the production status to be obtained from there in Vaadin 24.

### Describe solution expectations

My expectation is that the code should call [isProductionMode](https://vaadin.com/api/platform/current/com/vaadin/flow/server/AbstractConfiguration.html#isProductionMode())

**Comment by javier-godoy** [comment]
In version 2.0 of the add-on we had

https://github.com/FlowingCode/ErrorWindowAddon/blob/90137633f83098c9bbdd000d8264105ed13ffaac/error-window-vaadin/src/main/java/com/flowingcode/vaadin/addons/errorwindow/ErrorWindow.java#L185-L189
