### ISSUE TITLE
Custom message not shown on Production mode

### ISSUE THREAD

**Issue by FedericoQuarin** [FlowingCode/ErrorWindowAddon#81]
### Describe the bug

On production mode, the error window is not showing the custom message that was set, just the error code.
![errorWindow](https://github.com/FlowingCode/ErrorWindowAddon/assets/54511211/59861bc2-37c4-4ccf-bc1b-b08fc3c0201d)

### Minimal reproducible example

On the demo, setting production mode and clicking _Throw Error with custom message_

### Add-on Version

4.0.1

### Vaadin Version

24

**Comment by javier-godoy** [comment]
The default error handler initializes `errorMessage` from the `throwable.getLocalizedMessage()` (which, regardless of its name, is almost never localized). For unexpected exceptions, it does not make sense to display that information to final users.

You can configure a custom ErrorWindowFactory for a given exception class (and initialize the error window there as you see fit)
https://github.com/FlowingCode/ErrorWindowAddon/blob/24aae5a27bff7852529e1afc5997dfc9b2a6045b/src/main/java/com/flowingcode/vaadin/addons/errorwindow/ErrorManager.java#L79C22-L82

Alternatively, you can provide custom "instructions" and open `ErrorWindow` explicitly:

https://github.com/FlowingCode/ErrorWindowAddon/blob/24aae5a27bff7852529e1afc5997dfc9b2a6045b/src/test/java/com/flowingcode/vaadin/addons/errorwindow/ErrorwindowDemo.java#L75-L92

**Comment by javier-godoy** [comment]
The constructor `(Throwable, String)` seems to suggest that the string will be displayed as "instructions" (in production mode) and that it will override the exception message (in development mode). As explained above, this is not the current intention of the API, but we acknowledge that it's not good DX.

**Comment by mlopezFC** [comment]
Maybe we could deprecate that constructor to emphasize that.
