### ISSUE TITLE
Sometimes the production checkbox is not working

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/ErrorWindowAddon#82]
### Describe the bug

Sometimes the production mode checkbox is not checked but the exception is shown in production mode, see this screenshot:

![image](https://github.com/FlowingCode/ErrorWindowAddon/assets/28312758/18a26b4e-1b65-4b91-a258-4537fdb94a94)

### Expected behavior

If the production mode checkbox is enabled, the feature must be activated

### Minimal reproducible example

I do not have a 100% reproducible example, but if you play around with the checkbox with two opened browser the issue will happen

### Add-on Version

4.0.1-SNAPSHOT

### Vaadin Version

24

### Additional information

I think that it might be related to a concurrency issue

**Comment by javier-godoy** [comment]
I had fixed it in 4.1.1-SNAPSHOT demos, but staging site was not using the latest snapshot.

https://github.com/FlowingCode/ErrorWindowAddon/blob/24aae5a27bff7852529e1afc5997dfc9b2a6045b/src/test/java/com/flowingcode/vaadin/addons/errorwindow/ErrorwindowDemo.java#L105-L114
