### ISSUE TITLE
Buttons are floating if message is expanded

### ISSUE THREAD

**Issue by Dudeplayz** [FlowingCode/ErrorWindowAddon#83]
### Describe the bug

When the error message is expanded, the buttons start to float above the content:
<img width="800" alt="CleanShot 2024-08-02 at 14 59 38@2x" src="https://github.com/user-attachments/assets/753e8f45-f41d-4f3d-855b-c5d7e60d51f5">

### Expected behavior

Content and buttons are aligned properly.

### Add-on Version

4.1.0

### Vaadin Version

24.4.7

**Comment by paodb** [comment]
Hi, please check that _com.flowingcode_ is added to the [allowed-packages property](https://vaadin.com/docs/latest/flow/integrations/spring/configuration/#configure-the-scanning-of-packages) in your application.properties file.

**Comment by Dudeplayz** [comment]
I'm using quarkus, so I had to adapt my application.properties scanning the files:
```
quarkus.index-dependency.flowingcode.group-id=com.flowingcode.vaadin.addons
quarkus.index-dependency.flowingcode.artifact-id=error-window-vaadin (optional)
```

Sorry and thanks for the effort!
Maybe you'd like to add a jandex directly to the addon?
https://vaadin.com/docs/latest/flow/integrations/quarkus#quarkus.vaadin.addons

**Comment by javier-godoy** [comment]
@Dudeplayz I've just added a jandex index to version 4.1.1-SNAPSHOT (available from https://maven.flowingcode.com/snapshots/). Can you give it a try?

**Comment by Dudeplayz** [comment]
> @Dudeplayz I've just added a jandex index to version 4.1.1-SNAPSHOT (available from https://maven.flowingcode.com/snapshots/). Can you give it a try?

Sorry for the late reply.
I now tried to replicate the wrong behavior, by not building the jandex by myself. Unfortunately I wasn't able to reproduce it.
I am also now on vaadin v24.5.3, don't know if there were some changes.
